extends:
  - 'airbnb-typescript/base'
  - plugin:import/recommended

parserOptions:
  project: './tsconfig.json'

rules:
  object-curly-spacing: [error, always]
  template-curly-spacing: [error, always]
  import/prefer-default-export: off
  class-methods-use-this: off
  object-curly-newline: [error, { consistent: true }]
  import/no-extraneous-dependencies: off
  max-len: [warn, 140]
  no-useless-return: off
  consistent-return: off
  brace-style: [error, 1tbs, { allowSingleLine: false }]
  curly: [error, all]
  no-await-in-loop: off
  no-restricted-syntax: off
  no-multiple-empty-lines: [error, { max: 1 }]
  arrow-parens: [error, as-needed, { requireForBlockBody: true }]
  "@typescript-eslint/no-unused-vars": [error, { argsIgnorePattern: "^_" }]

  padding-line-between-statements:
    - error
    - blankLine: always
      prev: "*"
      next: if
    - blankLine: always
      prev: "*"
      next: return
    - blankLine: always
      prev: "*"
      next: throw
